apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: mper0003/app-admin
  name: app-admin
  namespace: backend
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|mper0003|app-admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: backend.admin@bigco.com
